name: Build

on:
  push:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: "^1.17.0"
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Catch singal
        run: |
          go build
          ./github-cancel-signal
